Update were-just-normal-repositories.json
github/ruleset-recipes pull request #20
Opened 2024-06-05 19:51 UTC by y-me-y

Add a quote to the value of the `"context":` key. It may had been left out on purpose but closing just in case. I'm not sure if I need to add quotes around the integration id but figured we could at least close the double quotes on this.

2024-06-05 23:45 UTC, patrick-knight requested changes
Let's also remove the single ticks

2024-06-05 23:45 UTC, patrick-knight commented on branch-rulesets/were-just-normal-repositories.json
> +                        "context": "`status check context name`",
```suggestion
                        "context": "status check context name",
```

2024-06-06 13:56 UTC, y-me-y commented
> Let's also remove the single ticks

Should we remove the single ticks from the value of the `integration_id`?

2024-06-07 16:14 UTC, patrick-knight commented on branch-rulesets/were-just-normal-repositories.json
>                          "integration_id": `integration ID that this status check must originate from.`
```suggestion
                        "integration_id": integration ID that this status check must originate from.
```

2024-06-07 18:40 UTC, patrick-knight approved these changes

2024-06-07 18:40 UTC, merged